using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Homura.SourceGenerator
{
    [Generator(LanguageNames.CSharp)]
    public class ChangePlanGenerator : IIncrementalGenerator
    {
        private const string GenerateChangePlanAttributeName = "Homura.ORM.Mapping.GenerateChangePlanAttribute";
        private const string VersionOriginFullName = "Homura.ORM.Mapping.VersionOrigin";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    GenerateChangePlanAttributeName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => GetChangePlanInfos(ctx))
                .Where(static x => x != null)
                .SelectMany(static (x, _) => x);

            context.RegisterSourceOutput(provider, static (spc, planInfo) =>
            {
                var source = GenerateChangePlanSource(planInfo);
                spc.AddSource($"ChangePlan_{planInfo.EntityName}_{planInfo.TargetVersionName}.g.cs", source);
            });
        }

        private static List<ChangePlanInfo> GetChangePlanInfos(GeneratorAttributeSyntaxContext context)
        {
            var symbol = (INamedTypeSymbol)context.TargetSymbol;
            var entityNamespace = symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : symbol.ContainingNamespace.ToDisplayString();

            var results = new List<ChangePlanInfo>();

            foreach (var attr in context.Attributes)
            {
                if (attr.AttributeClass?.ToDisplayString() != GenerateChangePlanAttributeName)
                    continue;

                var targetVersionType = attr.ConstructorArguments[0].Value as INamedTypeSymbol;
                if (targetVersionType == null) continue;

                INamedTypeSymbol fromVersionType = null;
                if (attr.ConstructorArguments.Length > 1)
                    fromVersionType = attr.ConstructorArguments[1].Value as INamedTypeSymbol;

                var targetVersionNumber = GetVersionNumber(targetVersionType);
                var targetTableName = GeneratePhysicalTableName(symbol.Name, targetVersionNumber);

                var info = new ChangePlanInfo
                {
                    EntityName = symbol.Name,
                    EntityFullName = symbol.ToDisplayString(),
                    Namespace = entityNamespace,
                    TargetVersionName = targetVersionType.Name,
                    TargetVersionFullName = targetVersionType.ToDisplayString(),
                    FromVersionName = fromVersionType?.Name,
                    FromVersionFullName = fromVersionType?.ToDisplayString(),
                    TargetTableName = targetTableName,
                    IsInitialCreation = fromVersionType == null,
                    DaoName = $"{symbol.Name}Dao",
                    Accessibility = symbol.DeclaredAccessibility,
                };
                results.Add(info);
            }

            return results;
        }

        private static int GetVersionNumber(INamedTypeSymbol versionType)
        {
            int depth = 0;
            var current = versionType;
            while (current != null && current.ToDisplayString() != VersionOriginFullName)
            {
                current = current.BaseType;
                depth++;
            }
            if (current == null) return 0;
            return depth;
        }

        private static string GeneratePhysicalTableName(string entityName, int versionNumber)
        {
            return versionNumber > 0 ? $"{entityName}_{versionNumber}" : entityName;
        }

        private static string GenerateChangePlanSource(ChangePlanInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            sb.AppendLine();
            sb.AppendLine("using Homura.ORM;");
            sb.AppendLine("using Homura.ORM.Migration;");
            sb.AppendLine("using Homura.ORM.Setup;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();

            if (info.Namespace != null)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            var accessibility = info.Accessibility == Accessibility.Public ? "public" : "internal";
            var className = $"ChangePlan_{info.EntityName}_{info.TargetVersionName}";

            sb.AppendLine($"    {accessibility} partial class {className} : ChangePlan<{info.EntityFullName}, {info.TargetVersionFullName}>");
            sb.AppendLine("    {");

            // Constructor
            sb.AppendLine($"        public {className}(VersioningMode mode)");
            sb.AppendLine($"            : base(\"{info.TargetTableName}\", PostMigrationVerification.TableExists, mode)");
            sb.AppendLine("        {");
            sb.AppendLine("        }");
            sb.AppendLine();

            // UpgradeToTargetVersion
            sb.AppendLine("        public override void UpgradeToTargetVersion(IConnection connection)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var dao = new {info.DaoName}(typeof({info.TargetVersionFullName}));");
            sb.AppendLine("            dao.CurrentConnection = connection;");

            if (info.IsInitialCreation)
            {
                // Initial table creation
                sb.AppendLine("            dao.CreateTableIfNotExists();");
                sb.AppendLine("            ++ModifiedCount;");
                sb.AppendLine("            dao.CreateIndexIfNotExists();");
                sb.AppendLine("            ++ModifiedCount;");
            }
            else
            {
                // Upgrade from previous version
                sb.AppendLine($"            dao.UpgradeTable(new VersionChangeUnit(typeof({info.FromVersionFullName}), typeof({info.TargetVersionFullName})), Mode);");
                sb.AppendLine("            ++ModifiedCount;");
            }

            sb.AppendLine("        }");

            // CreateTable
            sb.AppendLine();
            sb.AppendLine("        public override void CreateTable(IConnection connection)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var dao = new {info.DaoName}(typeof({info.TargetVersionFullName}));");
            sb.AppendLine("            dao.CurrentConnection = connection;");
            sb.AppendLine("            dao.CreateTableIfNotExists();");
            sb.AppendLine("            ++ModifiedCount;");
            sb.AppendLine("        }");

            // DropTable
            sb.AppendLine();
            sb.AppendLine("        public override void DropTable(IConnection connection)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var dao = new {info.DaoName}(typeof({info.TargetVersionFullName}));");
            sb.AppendLine("            dao.CurrentConnection = connection;");
            sb.AppendLine("            dao.DropTableIfExists();");
            sb.AppendLine("            ++ModifiedCount;");
            sb.AppendLine("        }");

            sb.AppendLine("    }");

            if (info.Namespace != null)
                sb.AppendLine("}");

            return sb.ToString();
        }

        private class ChangePlanInfo
        {
            public string EntityName { get; set; }
            public string EntityFullName { get; set; }
            public string Namespace { get; set; }
            public string TargetVersionName { get; set; }
            public string TargetVersionFullName { get; set; }
            public string FromVersionName { get; set; }
            public string FromVersionFullName { get; set; }
            public string TargetTableName { get; set; }
            public bool IsInitialCreation { get; set; }
            public string DaoName { get; set; }
            public Accessibility Accessibility { get; set; }
        }
    }
}
